### ISSUE TITLE
Any news with the encription key?

### ISSUE THREAD

**Issue by zallaevan** [borfast/arrispwgen#17]
There has been a lot of time since someone asked about the encryption key of the `router.data` file. Any news? I have a file here that needs decoding, but no luck so far...
Thx in advance

**Comment by borfast** [comment]
Hi @zallaevan,

I'm afraid there are no news. All I have is what's available on the [website](https://arrispwgen.borfast.com/). It's expected that those techniques work on less and less models as time goes by because the manufacturer will implement different security mechanisms. If the generated passwords don't work and the tricks to get the seed don't yield any results, I'm afraid I have no way of helping :slightly_frowning_face:

**Comment by zallaevan** [comment]
Oh, so sad to hear those news... I hope I can find something... Thank you anyways!
